name: Build API

on:
  release:
    types:
      - published
  push:
    branches:
      - ["main" "sub"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build API
        if: ${{ github.event_name == 'release' || (startsWith(github.event.head_commit.message, 'hotfix:') && github.ref == 'refs/heads/main')}}
        run: cd api && npm install && npm run build
