name: Merge Main to Stage

on:
  release:
    types:
      - published

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config --global user.name "KevinFernandoNT"
          git config --global user.email "kevin@nuclei.tech"
          git config pull.rebase false
          git fetch
          git checkout stage
          git pull origin main --allow-unrelated-histories
          git push origin/stage
