name: Merge Main to Stage

on:
  release:
    types:
      - published

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge branches
        run: |
          git config user.name "KevinFernandoNT"
          git config user.email "kevin@nuclei.tech"
          git fetch
          git checkout stage
          git merge origin/main --no-ff --no-edit --allow-unrelated-histories
          git push origin/stage
