name: Release new vertion

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build API
        run: cd api && npm install && npm run build
      - name: Build Web
        run: cd web && npm install && npm run build
      - run: npx semantic-release --config ./web/release.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
